landingpage/urls.py
from django.urls import path

from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.index, name='index'),
]

project_ppw/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from story_7.views import index, add_data, get_data
from story_8.views import index, search
from story_9.views import index, auth, api_login, api_sign_up, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    
    path('story-7/', include('story_7.urls')),
    path('add-data/', add_data, name='add-data'),
    path('get-data/', get_data, name='get-data'),

    path('story-8/', include('story_8.urls')),
    path('search/<str:keyword>', search, name='search'),
    path('search/', search, name='search'),

    path('story-9/', include('story_9.urls')),
    path('', index, name="home"),
    path('auth/', auth, name="authentication_page"),
    path('logout/', logout_user, name="logout"),
    path('api/v1/login/', api_login, name="login"),
    path('api/v1/signup/', api_sign_up, name="sign_up"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

story_7/urls.py
from django.urls import path, include
from .views import index,add_data,get_data

app_name = 'story_7'

urlpatterns = [
    path('', index, name='home'),
    path('add-data/', add_data, name='add-data'),
    path('get-data/', get_data, name='get-data'),
]   
    
  

story_8/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

# views
from story_8.views import index, search

app_name = 'story_8'

urlpatterns = [
    path('', index, name='home'),
    path('search/<str:keyword>', search, name='search'),
    path('search/', search, name='search'),
]

story_9/urls.py
from django.contrib import admin
from django.urls import path, include

from story_9.views import index, auth, logout_user, api_login, api_sign_up

app_name = 'story_9'

urlpatterns = [
    path('', index, name="homepage"),
    path('auth/', auth, name="authentication_page"),
    path('logout/', logout_user, name="logout"),
    path('api/v1/login/', api_login, name="login"),
    path('api/v1/signup/', api_sign_up, name="sign_up"),
]

landingpage/models.py
from django.db import models

# Create your models here.

story_7/models.py
from django.db import models

# Create your models here.

class AccordionItem(models.Model):
  title = models.CharField(max_length=500)
  content = models.TextField()

  def __str__(self):
    return f'{self.title}: {self.content}'

story_8/models.py
from django.db import models

# Create your models here.

story_9/models.py
from django.db import models

# Create your models here.

landingpage/views.py
from django.shortcuts import render
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.core import serializers

def index(request):
  return render(request, 'index.html')

story_7/views.py
from django.shortcuts import render
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.core import serializers

# models
from story_7.models import AccordionItem

def index(request):
  return render(request, 'main.html')

def get_data(request):
  serialized_items = serializers.serialize('json', AccordionItem.objects.all())
  return HttpResponse(serialized_items, content_type="text/json-comment-filtered")

def add_data(request):
  if request.method == 'POST':
    try:
      title = request.POST['title']
      content = request.POST['content']
    except KeyError:
      return HttpResponseBadRequest('Incomplete data')

    item = AccordionItem.objects.create(
      title=title,
      content=content
    )

    serialized_item = serializers.serialize('json', [item])

    return HttpResponse(serialized_item, content_type="text/json-comment-filtered")

  else:
    return HttpResponseBadRequest('Get request is not allowed')

story_8/views.py
# Django imports
from django.shortcuts import render, redirect
from django.http import JsonResponse

# Other imports
import requests
import json

# constants
API_URL = 'https://www.googleapis.com/books/v1/volumes?q='

def index(request):
  return render(request, 'main8.html')

def search(request, keyword=None):
  if keyword:
    response = requests.get(f'{API_URL}{keyword}')
    return JsonResponse({
      "status_code": response.status_code,
      "data": response.json()
    })

  else:
    return redirect('home')

story_9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt


import json

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        context = {
            'user': request.user
        }
        return render(request, 'main9.html', context)
    else:
        return redirect('/auth/')

def auth(request):
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    return redirect('/auth/')

@csrf_exempt
def api_login(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        if 'username' in data and 'password' in data:
            user = authenticate(request, username=data['username'], password=data['password'])

            if user is not None:
                login(request, user)
                return JsonResponse({
                    'status': 200,
                    'message': 'Sukses melakukan login'
                })
            else :
                try:
                    User.objects.get(username=data['username'])
                    return JsonResponse({
                        'status' : 401,
                        'message': 'Username / password salah, mohon periksa kembali dan coba lagi'
                    })
                except User.DoesNotExist:
                    return JsonResponse({
                        'status' : 401,
                        'message': 'Username tidak terdaftar, mohon periksa kembali dan coba lagi'
                    })

    return HttpResponseBadRequest()

@csrf_exempt
def api_sign_up(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        if 'username' in data and 'password' in data and 'email' in data:
            try:
                User.objects.create_user(data['username'], data['email'], data['password'])
                return JsonResponse({
                    'status': 200,
                    'message': 'Sukses membuat akun, silahkan login dengan akun yang anda buat!'
                })
            except:
                return JsonResponse({
                    'status' : 500,
                    'message': 'Username sudah dipakai, coba ganti dengan username lain'
                })
                
    return HttpResponseBadRequest()

landingpage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frehanza's PPW Project</title>

    
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">

  <!-- Styling -->
  <link rel="stylesheet" href="{% static 'css/index.css' %}">

</head>
<body>

    <h1 class="text">Welcome to <br> Frehanza's PPW Stories</h1>
    
    <div class="container">
        <a class="btn btn-1" href="http://story1-frehanza.herokuapp.com/Story1.html">Story 1</a>
        <a class="btn btn-2" href="https://www.figma.com/file/usBktZiZu5RbLUb9OYBTwM/PPW?node-id=12%3A3">Story 2</a>
        <a class="btn btn-3" href="https://story-frehanza.herokuapp.com/">Story 3-5</a> 
        <a class="btn btn-4" href="http://story6-frehanza.herokuapp.com/">Story 6</a> 
        <a class="btn btn-5" href="{% url 'story_7:home' %}">Story 7</a>
        <a class="btn btn-1" href="{% url 'story_8:home' %}">Story 8</a>
        <a class="btn btn-2" href="{% url 'story_9:authentication_page' %}">Story 9</a>
    </div>

</body>
</html>

story_7/templates/main.html
<!DOCTYPE html>

{% load static %}


<html lang="en">
<head>
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Frehanza | Story 7</title>

  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
 
  <!-- Styling -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <!-- JQuery Import -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

  <!-- Custom Script -->
  <script defer src="{% static 'js/main.js' %}"></script>
</head>
<body>

  <div class="logo">
    <a href="{% url 'landingpage:index' %}"><img src="{% static 'favicon-32x32.png' %}" alt="F"></a>
  </div>

  <div id="wrapper">

    <h1 class="text">Accordion</h1>

    <form id="paper" method="POST" action="{% url 'story_7:home' %}">
    {% csrf_token %}

    <div id="margin">Title: <input id="title-form" type="text" name="title"></div>

    <textarea placeholder="Enter something here..." id="text-form" name="content" rows="4" style="overflow: hidden; word-wrap: break-word; resize: none; height: 160px; "></textarea>  
    <br>

    <button id="button">Submit</button>

    
    </form>
    
  </div>

<div id='accordion'></div>
</body>
</html>

story_8/templates/main8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Styling -->
  <link rel="stylesheet" href="{% static 'main8.css' %}">

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <!-- <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&display=swap" rel="stylesheet"> -->

  <title>Story 8</title>
</head>
<body>
  <main>
    <div class="jumbotron">
      <h1>Search Books</h1>
      <form id="search-box">
    
        <input type="text" name="keyword" placeholder="Search some books...">
        <button type="submit" id="search-btn">
          <img src="{% static 'search-icon.svg' %}" alt="">
        </button>
      </form>
    </div>
    <h2 id="search-result-count"></h2>
    <table class="search-results"></table>
  </main>
</body>
<!-- JS Scripts -->
<script defer src="{% static 'main8.js' %}"></script>
</html>

story_9/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
    <title>Login Page</title>
</head>
<body>
    <div class="main-login">
        <div class="login-section">
            <div id="logIn" class="auth-section">
                <h1 class="login-header">Log in to your account</h1>
                <div class="error-message"></div>
                <div class="success-message"></div>
                <div class="label-group">
                    <label class="input-label">Username</label>
                    <div class="input-group">
                        <input type="text" placeholder="Type your username" class="input" name="username" autocomplete="off">
                    </div>
                </div>
                <div class="label-group">
                    <label class="input-label">Password</label>
                    <div class="input-group">
                        <input type="password" placeholder="Type your password" class="input" name="password">
                    </div>
                </div>
                <a href="{% url 'story_9:homepage' %}"><button class="main-button" id="logInButton"></a>
                <a href="{% url 'story_9:homepage' %}"></a><div class="lds-ring loading-hide"><div></div><div></div><div></div><div></div></div></a>
                <a href="{% url 'story_9:homepage' %}"><div class="button-inner">Log In</div></a>
                </button>
                <a id="createAccountLink" class="create-new">Don't have an account? Create an account</a>
            </div>
            <div id="signUp" class="auth-section hide">
                <h1 class="login-header">Create new account</h1>
                <div class="error-message"></div>
                <div class="success-message"></div>
                <div class="label-group">
                    <label class="input-label">Username</label>
                    <div class="input-group">
                        <input type="text" placeholder="Type your username" class="input" name="s_username" autocomplete="off">
                    </div>
                </div>
                <div class="label-group">
                    <label class="input-label">Email</label>
                    <div class="input-group">
                        <input type="email" placeholder="test@gmail.com" class="input" name="s_email">
                    </div>
                </div>
                <div class="label-group">
                    <label class="input-label">Password</label>
                    <div class="input-group">
                        <input type="password" placeholder="Type your password" class="input" name="s_password">
                    </div>
                </div>
                <button class="main-button" id="signUpButton">
                    <div class="button-inner">Sign Up</div>
                </button>
                <a id="loginLink" class="create-new">Already have account ? click here to login</a>
            </div>
        </div>
    </div>
    <script src="{% static 'main.js' %}"></script>
</body>
</html>

story_9/templates/main9.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
    <title>Hi {{user}} !</title>
</head>
<body>
    <div class="homepage">
        Hi <div class="span1">{{ user }}</div> !<br>
        <div class="homepage-subtitle">
            Selamat datang di Website story 9!
        </div>
        <img src="https://media.giphy.com/media/4N3Mqhl8JRyYLapZgt/giphy.gif" class="welcome">
        <br>
        <a href="{% url 'story_9:logout' %}"><button class="main-button logout-button">Logout </button></a>
    </div>
</body>
</html>